import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SuggestedUsers from "@/components/SuggestedUsers";
import TrendingTopics from "@/components/TrendingTopics";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="relative z-20 min-h-screen w-full flex flex-col" style={{ backgroundColor: '#18181c' }}>
            <Header />
              <div className="mx-auto w-full max-w-3xl flex flex-row justify-center relative border-l border-r border-white/30">
                <main className="w-full z-10 min-h-screen bg-black px-0" style={{ backgroundColor: '#18181b' }}>{children}</main>
              <aside className="hidden xl:flex flex-col gap-6 fixed right-8 top-24 w-[320px]">
                <SuggestedUsers />
                <TrendingTopics />
              </aside>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
